Upload DB to FTP server and fetch from FTP server.

diff --git a/dbackup b/dbackup
--- a/dbackup
+++ b/dbackup
@@ -1,14 +1,9 @@
 #!/usr/bin/env php
 <?php
+require_once 'dbackup-config.php';
+
 date_default_timezone_set('Asia/Dhaka');
-// define("BACKUP_PATH", realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR . 'DB_Backups' . DIRECTORY_SEPARATOR);
-define("BACKUP_PATH", realpath(dirname(__FILE__). '/DB_Backups'));
-$GLOBALS['server_name']   = "localhost";
-// $GLOBALS['username']      = "root";
-// $GLOBALS['password']      = "root";
-// $GLOBALS['database_name'] = "test_db_1";
 $GLOBALS['date_string']   = date("Y-m-d_his_A");
-$GLOBALS['keep_db'] = 5;
 
 function get_path($software = '') {
     $GLOBALS['mysqldump_path'] = '';
@@ -69,10 +64,13 @@ function backup($software = '') {
     // $cmd = "mysqldump --routines -h {$GLOBALS['server_name']} -u {$GLOBALS['username']} -p{$GLOBALS['password']} {$GLOBALS['database_name']} > " . BACKUP_PATH . "{$GLOBALS['date_string']}_{$GLOBALS['database_name']}.sql";
 
     if(($software == 'xampp') || ($software == 'vagrant')) {  // For Xampp and Vagrant
-
-        $cmd = "{$GLOBALS['mysqldump_path']} --routines -h {$GLOBALS['server_name']} -u {$GLOBALS['username']} -p{$GLOBALS['password']} {$GLOBALS['database_name']} > " . BACKUP_PATH . DIRECTORY_SEPARATOR . "{$GLOBALS['date_string']}_{$GLOBALS['database_name']}.sql";
+        $db_file_name = "{$GLOBALS['date_string']}_{$GLOBALS['database_name']}.sql";
+        $cmd = "{$GLOBALS['mysqldump_path']} --routines -h {$GLOBALS['server_name']} -u {$GLOBALS['username']} -p{$GLOBALS['password']} {$GLOBALS['database_name']} > " . BACKUP_PATH . DIRECTORY_SEPARATOR . $db_file_name;
         exec($cmd);
 
+        if($GLOBALS['ftp_sync'] == 'yes') {
+            ftp_db_upload($db_file_name);
+        }
     } elseif($software == 'docker') {  // For Docker
 
         echo "Enter MySQL Container Name: ";
@@ -91,6 +89,9 @@ function backup($software = '') {
 
         // echo PHP_EOL . 'text from docker - backup fn';
 
+        if($GLOBALS['ftp_sync'] == 'yes') {
+            ftp_db_upload($db_file_name);
+        }
     } else {
         //
     }
@@ -140,20 +141,99 @@ function restore($software = '') {
     // echo 'text from restore fn';
 }
 
-if (array_key_exists("1", $argv) && array_key_exists("2", $argv) && (($argv[1] == 'backup') || ($argv[1] == 'restore')) && (($argv[2] == 'xampp') || ($argv[2] == 'docker') || ($argv[2] == 'vagrant'))) {
-    if (function_exists($argv[1])) {
-        echo "Enter MySQL User Name: ";
-        $GLOBALS['username'] = trim(fgets(fopen("php://stdin","r")));
-        echo "Enter MySQL Password: ";
-        $GLOBALS['password'] = trim(fgets(fopen("php://stdin","r")));
-        echo "Enter MySQL Database Name: ";
-        $GLOBALS['database_name'] = trim(fgets(fopen("php://stdin","r")));
-
-        get_path($argv[2]);
-        echo $argv[1]($argv[2]);
-    } else {
-        echo 'Please Provide Correct Argument - backup/restore';
+function ftp_db_upload($file_upload) {
+    $ftp_conn = ftp_connect($GLOBALS['ftp_server']) or die("Could not connect to {$GLOBALS['ftp_server']}");
+    $login = ftp_login($ftp_conn, $GLOBALS['ftp_username'], $GLOBALS['ftp_password']);
+    
+    // open file for reading
+    $file = BACKUP_PATH . DIRECTORY_SEPARATOR . $file_upload;
+    if(file_exists($file)) {
+        $fp = fopen($file,"r");
+        // upload file
+        if (ftp_fput($ftp_conn, $GLOBALS['ftp_path'] . '/' . $file_upload, $fp, FTP_ASCII)) {
+          echo "Successfully uploaded $file." . PHP_EOL;
+        } else {
+          echo "Error uploading $file.";
+        }
+        // close file handler
+        fclose($fp);
     }
-} else {
-    echo 'Please Provide Argument-1 (backup/restore) and Argument-2 (xampp/docker/vagrant)' . PHP_EOL;
+
+    // get the file list for /
+    $ftp_filelist = array_reverse(ftp_nlist($ftp_conn, $GLOBALS['ftp_path']));
+    foreach($ftp_filelist as $ftp_file_key=>$ftp_file_value) {
+        if(($ftp_file_key >= $GLOBALS['keep_db']) && ($ftp_file_value != ".") && ($ftp_file_value != "..") && ($ftp_file_value != ".htaccess")) {
+            // try to delete file
+            if (ftp_delete($ftp_conn, $GLOBALS['ftp_path'] . '/' . $ftp_file_value)) {
+                echo "$ftp_file_value deleted" . PHP_EOL;
+            } else {
+                echo "Could not delete $ftp_file_value";
+            }
+        }
+    }
+    
+    // close this connection
+    ftp_close($ftp_conn);
 }
+
+function ftp_db_fetch() {
+    $ftp_conn = ftp_connect($GLOBALS['ftp_server']) or die("Could not connect to {$GLOBALS['ftp_server']}");
+    $login = ftp_login($ftp_conn, $GLOBALS['ftp_username'], $GLOBALS['ftp_password']);
+    
+    // get the file list for /
+    $ftp_filelist = ftp_nlist($ftp_conn, $GLOBALS['ftp_path']);
+    
+    // output $filelist
+    // var_dump($ftp_filelist);
+
+    foreach($ftp_filelist as $ftp_file) {
+        if(($ftp_file == ".") || ($ftp_file == "..") || ($ftp_file == ".htaccess")) {
+            continue;
+        } else {
+            $server_file = $GLOBALS['ftp_path'] . '/' . $ftp_file;
+            // open local file to write to
+            $create_file = BACKUP_PATH . DIRECTORY_SEPARATOR . $ftp_file;
+            if(file_exists($create_file)) {
+                continue;
+            } else {
+                $fp = fopen($create_file,"w");
+
+                // download server file and save it to open local file
+                if (ftp_fget($ftp_conn, $fp, $server_file, FTP_ASCII, 0)) {
+                    echo "Successfully written to $create_file." . PHP_EOL;
+                } else {
+                    echo "Error downloading $server_file." . PHP_EOL;
+                }
+                fclose($fp);
+            }
+        }
+    }
+
+    // var_dump($db_files);
+
+    // close connection
+    ftp_close($ftp_conn);
+}
+
+if(array_key_exists("1", $argv) && ($argv[1] == 'fetch')) {
+    ftp_db_fetch();
+} else {
+    if (array_key_exists("1", $argv) && array_key_exists("2", $argv) && (($argv[1] == 'backup') || ($argv[1] == 'restore')) && (($argv[2] == 'xampp') || ($argv[2] == 'docker') || ($argv[2] == 'vagrant'))) {
+        if (function_exists($argv[1])) {
+            // echo "Enter MySQL User Name: ";
+            // $GLOBALS['username'] = trim(fgets(fopen("php://stdin","r")));
+            // echo "Enter MySQL Password: ";
+            // $GLOBALS['password'] = trim(fgets(fopen("php://stdin","r")));
+            // echo "Enter MySQL Database Name: ";
+            // $GLOBALS['database_name'] = trim(fgets(fopen("php://stdin","r")));
+    
+            get_path($argv[2]);
+            echo $argv[1]($argv[2]);
+        } else {
+            echo 'Please Provide Correct Argument - backup/restore';
+        }
+    } else {
+        echo 'Please Provide Argument-1 (backup/restore) and Argument-2 (xampp/docker/vagrant)' . PHP_EOL;
+    }
+}
+
